variables:
  REGISTRY_HOST: ipe-wim-gitlab.fzi.de:5000
  IMAGE_NAME: $REGISTRY_HOST/$CI_PROJECT_PATH
  HARBOR_REGISTRY_HOST: laus.fzi.de:8201
  HARBOR_IMAGE_NAME:  $HARBOR_REGISTRY_HOST/$CI_PROJECT_PATH
  MAVEN_CLI_OPTS: -DskipTests --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true
  GIT_STRATEGY: clone

stages:
  - build
  - docker

build:
  image: maven:3-jdk-8
  stage: build
  script:
    - echo "$MAVEN_CREDENTIALS" > /root/.m2/settings.xml
    - mvn clean package -U -DskipTests
    - export MVN_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\[')
    - "echo $MVN_VERSION >> ./target/mvn_version"
  artifacts:
    paths:
      - ./*/target/*.jar
      - ./target/mvn_version
    expire_in:  1 hour
  except:
      - /release-.*$/


.docker_script: &docker_script
   image: docker:17.06.0-ce
   stage: docker
   dependencies:
     - build
   script:
     - export MVN_VERSION=$(cat ./target/mvn_version)
     - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY_HOST
     - docker login -u riemer -p $HARBOR_PASSWORD laus.fzi.de:8201
     - docker build --no-cache --pull -t $IMAGE_NAME/$CONTAINER_NAME:latest -t $IMAGE_NAME/$CONTAINER_NAME:$MVN_VERSION -t $HARBOR_IMAGE_NAME/$CONTAINER_NAME:latest -t $HARBOR_IMAGE_NAME/$CONTAINER_NAME:$MVN_VERSION .
     - docker push $IMAGE_NAME/$CONTAINER_NAME:$MVN_VERSION
     - docker push $IMAGE_NAME/$CONTAINER_NAME:latest
     - docker push $HARBOR_IMAGE_NAME/$CONTAINER_NAME:$MVN_VERSION
     - docker push $HARBOR_IMAGE_NAME/$CONTAINER_NAME:latest

docker-processors-azure:
    <<: *docker_script
    variables:
      CONTAINER_NAME: "processors-azure-vision"


