version: "2"
services:
  processors-transformation-jvm:
    image: ${SP_DOCKER_REGISTRY}/hackzurich/processors-azure-vision:${SP_PE_VERSION}
    depends_on:
      - "consul"
#    ports:
#      - "8098:8090"
    environment:
      - SP_ICON_HOST=${SP_ICON_HOST}
    networks:
      spnet:

